spring:
  application:
    name: school
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQLInnoDBDialect
      naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
      ddl-auto: create
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/lansingcarworkshop
    username: root
    password: root
  jackson:
    serialization:
      fail-on-empty-beans: false

server:
  context-path: /api

logging:
  level:
    prg.springframework.web: DEBUG
    org.hibernate: ERROR
    com.example.school: INFO